-- ---------------------------------------------------------------------------
-- Seed the CMS tables with the portfolio content (mirrors lib/content.ts).
-- Safe to re-run: clears each table first.
-- ---------------------------------------------------------------------------

truncate public.experience, public.pm_projects, public.ai_projects, public.certifications;

insert into public.experience (sort_order, logo_url, logo_alt, title, company, location, period, bullets) values
(0, '/zerofox-logo.png', 'ZeroFox logo', 'Cybersecurity Intelligence Analyst', 'ZeroFox', 'Bengaluru', 'January 2025 – August 2025',
 '[
   {"text": "Defined and scoped 50+ intelligence briefs from ambiguous requirements, collaborating with stakeholders to deliver insights that influenced product decisions and reduced response time by 30%."},
   {"text": "Synthesized complex technical data into strategic product recommendations, preparing reports adopted by C-suite, engineering, and client teams — contributing to a 25% improvement in stakeholder engagement."},
   {"text": "Applied risk-based prioritization frameworks to triage and resolve high-impact threats under strict SLAs, mirroring product backlog management and improving team throughput by 20%."},
   {"text": "Awarded the Pinnacle Award for leading critical mitigation of a malicious activity, demonstrating decisive leadership and product-oriented problem solving during high-stress incidents.", "highlight": true}
 ]'::jsonb);

insert into public.pm_projects (sort_order, slug, name, description, role, tools, outcome) values
(0, 'tripadvisor-qreview', 'Tripadvisor — QReview (Scan and Review)',
 'A feature that lets travelers scan QR codes at venues to instantly give structured ratings and quick reviews in exchange for redeemable “TACoins,” simplifying the review process and boosting platform engagement.',
 'Product Manager (Growth & Engagement)',
 'Similarweb (traffic analytics & secondary research), UI/UX wireframing tools',
 'Reduced user friction and drop-offs, increased platform traffic, boosted secondary bookings via TACoins — tracked via North Star Metric: number of reviews posted per month.'),
(1, 'cult-nutrition', 'Cult : Nutrition',
 'A personalized nutrition profiling and meal-planning subscription feature designed to build a holistic health ecosystem and drive cross-selling revenue through Eat.fit pre-orders.',
 'Product Manager (Growth Team)',
 'Figma (user journey mapping, interactive wireframing)',
 'Created a new subscription model targeting retention and trial conversion, reduced acquisition costs via cross-orders — tracked via North Star Metric: revenue generated by pre-orders from the Nutrition vertical.'),
(2, 'swiggy-homeyum', 'Swiggy HomeYum',
 'A hyperlocal marketplace within the Swiggy app connecting users with verified home-chefs for healthy, subscription-based native cuisine deliveries.',
 'Product Manager (New Product Vertical / Expansion)',
 'Prototyping software, system architecture/design tools',
 'Projected annual revenue potential of ₹1,080 Cr (~$130M), enabled home-chefs to earn ~₹25,200/month, captured a new health-conscious user segment — tracked via North Star Metric: number of successful subscription meals delivered per week.');

insert into public.ai_projects (sort_order, slug, name, description, tech_stack, case_study) values
(0, 'ai-client-readiness', 'AI-Powered Client Readiness & Assessment Tool',
 'An AI-driven evaluation platform that standardizes technical and domain readiness assessments through context-aware questioning, automated rubrics, and objective manager dashboards.',
 'Python, OpenAI API / LLMs, Vector Databases, Proctoring & Analytics APIs',
 'Led 0→1 development; designed modular knowledge bases and role-skill mapping; results included 40% faster ramp-up, 30% reduction in manager evaluation time, 80%+ completion on micro-assessments, and 60%+ reduction in manual evaluation effort — adopted by a major e-commerce enterprise client.'),
(1, 'ai-data-storytelling', 'AI-Powered Data Storytelling Platform',
 'A collaborative platform that transforms raw, fragmented business data into interactive, AI-driven narrative stories to streamline insight-to-decision workflows.',
 'Figma (advanced interactive prototyping), Python, LLM orchestration (e.g. LangChain), Data/BI visualization APIs',
 'Led a 3-member team to deliver a validated prototype in 7 working days; mapped the “golden path” from data retrieval to final presentation; delivered 4 fully interactive flows; prototype became a launchpad for fundraising and enterprise user testing.');

insert into public.certifications (sort_order, title, issuer, date, issued_by) values
(0, 'AI-First Product Management', 'Airtribe', 'Completed December 16, 2025', 'Issued by Navneet Sharma, Co-Founder @ Airtribe');
